const SET_SINGER = 'SET_SINGER'
const SET_PLAYINGSTATE = 'SET_PLAYINGSTATE'
const SET_FULLSCREEN = 'SET_FULLSCREEN'
const SET_PLAYLIST = 'SET_PLAYLIST'
const SET_SEQUENCELIST = 'SET_SEQUENCELIST'
const SET_MODE = 'SET_MODE'
const SET_CURRENTINDEX = 'SET_CURRENTINDEX'

export { SET_SINGER,
  SET_PLAYINGSTATE,
  SET_FULLSCREEN,
  SET_PLAYLIST,
  SET_SEQUENCELIST,
  SET_MODE,
  SET_CURRENTINDEX
}