const SET_SINGER = 'SET_SINGER'
const SET_PLAYINGSTATE = 'SET_PLAYINGSTATE'
const SET_FULLSCREEN = 'SET_FULLSCREEN'
const SET_PLAYLIST = 'SET_PLAYLIST'
const SET_SEQUENCELIST = 'SET_SEQUENCELIST'
const SET_MODE = 'SET_MODE'
const SET_CURRENTINDEX = 'SET_CURRENTINDEX'
const SET_CURRENTSONG = 'SET_CURRENTSONG'
const SET_CURRENTLYRIC = 'SET_CURRENTLYRIC'
const SET_CURRENTDISC = 'SET_CURRENTDISC'
const SET_RANK = 'SET_RANK'
const SET_SEARCHHISTORY = 'SET_SEARCHHISTORY'
const SET_PLAYHISTORY = 'SET_PLAYHISTORY'
export { SET_SINGER,
  SET_PLAYINGSTATE,
  SET_FULLSCREEN,
  SET_PLAYLIST,
  SET_SEQUENCELIST,
  SET_MODE,
  SET_CURRENTINDEX,
  SET_CURRENTSONG,
  SET_CURRENTLYRIC,
  SET_CURRENTDISC,
  SET_RANK,
  SET_SEARCHHISTORY,
  SET_PLAYHISTORY
}